apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners-stream-ci
spec:
  replicas: replicas-placeholder
  template:
    spec:
      image: 'summerwind/actions-runner'
      dockerdWithinRunnerContainer: true
      priorityClassName: high-priority
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: stream-metadata-default
      repository: spring-cloud/stream-applications
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager-secret
      resources:
        requests:
          cpu: "1000m"
          memory: "1Gi"
      labels:
        - stream-ci
